import { NextRequest, NextResponse } from 'next/server';
import { supabase } from '@/lib/supabase';
import { validateAndMapCSV, CSV_COLUMN_MAPPING } from '@/lib/upload/csvValidator';
import { withAdminAuth } from '@/lib/upload/adminAuth';
import { Company } from '@/lib/types';

// This route is modular and can be completely removed without affecting the main app
// It's isolated in the admin directory and doesn't impact load time

async function handleUpload(req: NextRequest) {
  try {
    const formData = await req.formData();
    const file = formData.get('file') as File;
    const mode = formData.get('mode') as string || 'append'; // 'append' or 'replace'
    
    if (!file) {
      return NextResponse.json({ error: 'No file provided' }, { status: 400 });
    }

    if (!file.name.endsWith('.csv')) {
      return NextResponse.json({ error: 'Only CSV files are supported' }, { status: 400 });
    }

    // Parse CSV
    const csvText = await file.text();
    const lines = csvText.split('\n').filter(line => line.trim());
    
    if (lines.length < 2) {
      return NextResponse.json({ error: 'CSV file must contain headers and at least one row' }, { status: 400 });
    }

    const headers = lines[0].split(',').map(h => h.trim().replace(/"/g, ''));
    const csvData = [];

    for (let i = 1; i < lines.length; i++) {
      const values = lines[i].split(',').map(v => v.trim().replace(/"/g, ''));
      const row: any = {};
      
      headers.forEach((header, index) => {
        row[header] = values[index] || '';
      });
      
      csvData.push(row);
    }

    // Validate and map CSV data
    const validation = validateAndMapCSV(csvData, headers);

    if (!validation.isValid) {
      return NextResponse.json({
        error: 'CSV validation failed',
        details: validation.errors,
        warnings: validation.warnings,
        removedColumns: validation.removedColumns
      }, { status: 400 });
    }

    // Process data based on mode
    if (mode === 'replace') {
      // Clear existing data
      const { error: deleteError } = await supabase
        .from('companies')
        .delete()
        .neq('id', '00000000-0000-0000-0000-000000000000'); // Delete all except dummy
      
      if (deleteError) {
        return NextResponse.json({ error: 'Failed to clear existing data', details: deleteError }, { status: 500 });
      }
    }

    // Insert new data
    const companiesToInsert = validation.mappedData.map(company => ({
      ...company,
      // Ensure UUID is generated by database
      id: undefined 
    }));

    const { data, error } = await supabase
      .from('companies')
      .insert(companiesToInsert)
      .select();

    if (error) {
      return NextResponse.json({ error: 'Failed to insert companies', details: error }, { status: 500 });
    }

    return NextResponse.json({
      success: true,
      message: `Successfully uploaded ${data.length} companies`,
      stats: {
        uploaded: data.length,
        warnings: validation.warnings.length,
        removedColumns: validation.removedColumns.length,
        mode
      },
      details: {
        warnings: validation.warnings,
        removedColumns: validation.removedColumns,
        supportedColumns: Object.keys(CSV_COLUMN_MAPPING)
      }
    });

  } catch (error) {
    console.error('Upload error:', error);
    return NextResponse.json({ 
      error: 'Internal server error', 
      details: error instanceof Error ? error.message : 'Unknown error'
    }, { status: 500 });
  }
}

export const POST = withAdminAuth(handleUpload);

// Helper endpoint to get CSV template
export async function GET() {
  const headers = Object.keys(CSV_COLUMN_MAPPING);
  
  return NextResponse.json({
    template: headers.join(','),
    supportedColumns: headers,
    columnMapping: CSV_COLUMN_MAPPING,
    instructions: {
      required: ['W2'],
      optional: headers.filter(h => h !== 'W2'),
      formats: {
        'W2': 'Company name (required)',
        'Company Logo URL': 'Full URL to company logo',
        'Latest News': 'JSON array: [{"title":"News title","url":"news_url"}]',
        'Technologies': 'JSON array or comma-separated: ["React","Node.js"]',
        'LinkedIn Followers': 'Number (commas allowed)',
        'Last Updated': 'Date string or ISO format'
      }
    }
  });
}
